#!/usr/bin/env python

import sys

from fetcher.utils import get_config_dataset, update_dafter, \
    uninstall_dafter
from fetcher.fetcher import get_dataset, delete_dataset, list_datasets, \
    info_dataset, search_datasets


HELP_MESSAGE = """usage: dafter [get dataset-name] [delete dataset-name] [info dataset-name] [update] [uninstall] [list] [search tag0 .. tagN]

Fetches all kind of datasets, whatever the format. Without pain.

Positional arguments:
  get dataset-name        Downloads and saves the dataset files
  delete dataset-name     Deletes the dataset files from the disk
  info dataset-name       Describes the dataset
  update                  Updates dafter
  uninstall               Uninstalls dafter
  list                    Lists all the datasets that are in database
  search tag0 .. tagN     Lists all the datasets available with these tags
"""

args = sys.argv[1:]

if args:
    action = args[0]
    if action not in ["get", "delete", "list", "search", "info", "update", "uninstall", "help"]:
        print("This command `dafter {}` does not exist\n".format(action))
        print(HELP_MESSAGE)

    args = args[1:]

    if action in ["help"]:
        print(HELP_MESSAGE)
    elif action in ["update"]:
        update_dafter()
    elif action in ["uninstall"]:
        uninstall_dafter()
    elif args and action in ["get", "delete", "info"]:
        datasetname = args[0]
        dataset_config = get_config_dataset(datasetname)
        if dataset_config:
            if action == "get":
                get_dataset(dataset_config)
            elif action == "delete":
                delete_dataset(dataset_config)
            elif action == "info":
                info_dataset(dataset_config)
        else:
            print("The dataset `{}` does not exist".format(datasetname))
    elif args and action in ["search"]:
        tags = ",".join(args).split(",")
        tags = [t.strip() for t in tags]
        search_datasets(tags)
    elif action in ["list"]:
        list_datasets()
    elif not args:
        if action in ["search"]:
            print("A tag is required\n")
            print(HELP_MESSAGE)
        elif action in ["get", "delete", "info"]:
            print("A dataset name is required\n")
            print(HELP_MESSAGE)
    else:
        print(HELP_MESSAGE)
else:
    print(HELP_MESSAGE)
