#!/usr/bin/env python

import sys
import readline

from fetcher.utils import get_config_dataset, update_datafetcher
from fetcher.fetcher import get_dataset, delete_dataset, list_datasets, \
    info_dataset


args = sys.argv[1:]

if args:
    action = args[0]
    if action not in ["get", "delete", "list", "info", "update"]:
        raise Exception("Wrong action")
    args = args[1:]

    if action in ["update"]:
        update_datafetcher()
    elif args and action in ["get", "delete", "info"]:
        datasetname = args[0]
        dataset_config = get_config_dataset(datasetname)
        if dataset_config:
            if action == "get":
                get_dataset(dataset_config)
            elif action == "delete":
                delete_dataset(dataset_config)
            elif action == "info":
                info_dataset(dataset_config)
            else:
                print("No action")
        else:
            raise Exception("The dataset does not exist")
    elif args and action in ["list"]:
        tag = args[0]
        list_datasets(tag)
    else:
        raise Exception("No dataset/No tag")
else:
    raise Exception("No args")
